# based on https://hub.docker.com/r/sparanoid/php-fpm
version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
      # Enable 443 on production
      # - 443:443
    depends_on:
      - php
    volumes:
      - ./php/src:/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    image: sparanoid/php-fpm:8-latest
    restart: always
    volumes:
      - ./php/src:/app