version: "3"
services:
  nginx:
    image: nginx
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./php/src/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-cli
    networks:
      - internal
    volumes:
      - ./php/src/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge